// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2RNLovSDfP4vgLZaW6Rdaaupeuir2RJA',
    appId: '1:745616957132:web:24de83f6e9d6b3209aec69',
    messagingSenderId: '745616957132',
    projectId: 'bouggr-4bd2b',
    authDomain: 'bouggr-4bd2b.firebaseapp.com',
    storageBucket: 'bouggr-4bd2b.appspot.com',
    measurementId: 'G-E8QSBZ8K35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDCkn_gtVVo1bty48DehabD9f2cXdlzfY',
    appId: '1:745616957132:android:4acef77112419aa89aec69',
    messagingSenderId: '745616957132',
    projectId: 'bouggr-4bd2b',
    storageBucket: 'bouggr-4bd2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZYOXbK_iNZgtYjwtdyVl2CdgLoUCBp-0',
    appId: '1:745616957132:ios:1590a3309202a7a49aec69',
    messagingSenderId: '745616957132',
    projectId: 'bouggr-4bd2b',
    storageBucket: 'bouggr-4bd2b.appspot.com',
    iosClientId:
        '745616957132-6d230q3fsi7e6d2hi5vhdr0cmabl5jte.apps.googleusercontent.com',
    iosBundleId: 'com.example.bouggr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZYOXbK_iNZgtYjwtdyVl2CdgLoUCBp-0',
    appId: '1:745616957132:ios:e94f9abeb9f2f9a99aec69',
    messagingSenderId: '745616957132',
    projectId: 'bouggr-4bd2b',
    storageBucket: 'bouggr-4bd2b.appspot.com',
    iosClientId:
        '745616957132-jej3hcgg8k8kn8pc67d3aujqtdgekuf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bouggr.RunnerTests',
  );
}
